- pystarport/cluster.py
- pystarport/cosmoscli.py
Solutoin: add query_denom_by_name
> Problem: missing support query_denom_by_name of NFT (fix #5)

- CHANGELOG.md
- pyproject.toml
- Add `query_denom_by_name` to check existing denom before issuing
- Add mnemonic option field for accounts
> release v0.2.1

- pystarport/cluster.py
Solution: adding back mnemonic field
> Problem: (#12)mnemonic field is accidentally deleted in accounts generation

- CHANGELOG.md
- pyproject.toml
> release v0.2.2

- pystarport/cluster.py
adjusted the relayer config, task ini + command arguments
in hermes 0.5/0.6+ , there doesn't seem to be individual path configuration (one can configure some filtering, but the default is all paths), hence making a single task
> fixed hermes config and startup according to the latest hermes changes

- README.md
Solution:
- add faq section in README
> Problem: 'AF_UNIX path too long' solution is not documented

- flake.lock
- flake.nix
```
$ nix run
$ nix build
$ nix develop
> nix flakify pystarport

- pyproject.toml
Solution:
- shouldn't included as package data file, include in source tarball is enough.
> Problem: license file is included as package data

- pystarport/cli.py
Solution:
- add --no_remove flag
> Problem: don't support option to keep existing data directory

- pystarport/cluster.py
Solution:
- should prefer cmd parameter passed in cli over the one in config file.
> Problem: cmd parameter passed in cli is not used

- pystarport/cli.py
- pystarport/cluster.py
Solution:
- set default cmd to None, resolve the correct one later
> Problem: default cmd is wrong

- pystarport/cluster.py
Closes: #45
Solution:
- support new field names
> Problem: don't work on tendermint 0.35

- CHANGELOG.md
- pyproject.toml
- boost version
- add missing changelogs
> prepare 0.2.4 release

- pystarport/utils.py
Solution:
- let caller decide how to handle stderr
> Problem: interact utility don't support custom stderr handling

- pystarport/cluster.py
Solution:
- fix the issue with custom key_name
> Problem: don't support custom key_name config

- pystarport/cluster.py
> Problem: old hermes config is used (fix #62)

- LICENSE
Solution: Update files with copyright notice
> Problem: Copyright attribution has to be updated

- pystarport/cluster.py
https://github.com/informalsystems/ibc-rs/pull/2275
> Avoid use confusing flag after ibc-rs#2275

- CHANGELOG.md
- pystarport/cluster.py
- pystarport/cosmoscli.py
Closes: #72
Solution:
- support several optional fields in validator section
> Problem: not able to specify commission rates in gentx

- CHANGELOG.md
- pystarport/cluster.py
Solution:
- set strip_ansi in supervisor config
> Problem: node log files contains ansi color codes

- pystarport/bot.py
- pystarport/cluster.py
- pystarport/cosmoscli.py
- pystarport/tests/test_expansion/test_expansion.py
Closes: https://github.com/crypto-com/pystarport/issues/76
> fix: resource warnings

- pystarport/cluster.py
this change should have been included in https://github.com/crypto-com/pystarport/commit/08c5d488e620f6f0b0fd95b55b44731d327c6977
> fix: add directory for relayer log 

- CHANGELOG.md
- pystarport/cluster.py
Solution:
- fix the validator index
> Problem: grpc port in client.toml is wrong

- pystarport/cluster.py
for more info, see [max_gas](https://github.com/cosmos/relayer/pull/1178/files) and [extension_options](https://github.com/cosmos/relayer/pull/1179/files)
> feat: support max_gas and extension_options in relayer

- CHANGELOG.md
- pystarport/cluster.py
- pystarport/cosmoscli.py
for more [info](https://github.com/cosmos/cosmos-sdk/pull/12659/files)
> fix: replace block with sync broadcast mode

- CHANGELOG.md
- pystarport/cluster.py
this change should have been included in https://github.com/crypto-com/pystarport/commit/5dbd84361cc24bcebfa47d5078ce2692590283a5
> fix: add default for gas prices

- CHANGELOG.md
- pystarport/cluster.py
this change should have been included in https://github.com/crypto-com/pystarport/commit/5dbd84361cc24bcebfa47d5078ce2692590283a5
> make golang relayer optional

- pystarport/cluster.py
closes https://github.com/crypto-com/pystarport/issues/106
> add gas prices to gentx in init

- CHANGELOG.md
- pystarport/cluster.py
- pystarport/cosmoscli.py
add `migrate_keystore` for [keyring](https://github.com/cosmos/cosmos-sdk/commit/6cbbd6da750c6e69ab62445c39c8b9bcb2246328) migrate
> Problem: migrated key related log breaks json.loads

- pyproject.toml
Solution:
- update to poetry.core backend
> Problem: can't be built with poetry2nix

- .gitignore
- CHANGELOG.md
- pystarport/cosmoscli.py
- update the genesis commands, compatible with both pre-0.50 and 0.50.
~~NOTE: don't merge, it's breaking.~~
> Problem: sdk 0.50 not supported

- pystarport/cluster.py
for more info, https://github.com/cosmos/relayer/pull/1504/files
> Problem: debug-addr rename to debug-listen-addr in relayer

- .flake8
- CHANGELOG.md
- pystarport/cosmoscli.py
> Problem: event-query-tx-for not compatible with chain-main
